const initialState = {
  teamA: {
    id: 1,
    name: "Top 20 StarWars",
    team: [
      "Darth Vader",
      "Obi-Wan Kenobi",
      "Yoda",
      "Han Solo",
      "Chewbacca",
      "R2-D2",
      "Darth Maul",
      "Leia Organa",
      "Luke Skywalker",
      "Emperor Palpatine",
      "Boba Fett",
      "Lando Calrissian",
      "BB-8",
      "Jabba The Hutt",
      "Kylo Ren",
      "C-3P0",
      "Admiral Ackbar",
      "Rey",
      "Finn",
      "Greedo"
    ]
  },
  teamB: {
    id: 2,
    name: "Top 20 Marvels",
    team: [
      "Moon Knight",
      "Jessica Jones",
      "Blade",
      "Captain America",
      "Killmonger",
      "Wolverine",
      "Black Panther",
      "Spider-Man",
      "Ultron",
      "Ghost Rider",
      "Hulk",
      "Loki",
      "Black Bolt",
      "Captain Marvel",
      "Luke Cage",
      "Daredevil",
      "Spider-Woman",
      "Cyclops",
      "Silver Surfer"
    ]
  },
  chosenTeam: {
    id: 1,
    name: "Top 20 StarWars",
    team: [
      "Darth Vader",
      "Obi-Wan Kenobi",
      "Yoda",
      "Han Solo",
      "Chewbacca",
      "R2-D2",
      "Darth Maul",
      "Leia Organa",
      "Luke Skywalker",
      "Emperor Palpatine",
      "Boba Fett",
      "Lando Calrissian",
      "BB-8",
      "Jabba The Hutt",
      "Kylo Ren",
      "C-3P0",
      "Admiral Ackbar",
      "Rey",
      "Finn",
      "Greedo"
    ]
  },
  unchosenTeam: {
    id: 2,
    name: "Top 20 Marvels",
    team: [
      "Moon Knight",
      "Jessica Jones",
      "Blade",
      "Captain America",
      "Killmonger",
      "Wolverine",
      "Black Panther",
      "Spider-Man",
      "Ultron",
      "Ghost Rider",
      "Hulk",
      "Loki",
      "Black Bolt",
      "Captain Marvel",
      "Luke Cage",
      "Daredevil",
      "Spider-Woman",
      "Cyclops",
      "Silver Surfer"
    ]
  }
};
export default initialState;
